const daysData = {
      1: { hiragana: 'ついたち', romaji: ['tsuitachi'] },
      2: { hiragana: 'ふつか', romaji: ['futsuka'] },
      3: { hiragana: 'みっか', romaji: ['mikka'] },
      4: { hiragana: 'よっか', romaji: ['yokka'] },
      5: { hiragana: 'いつか', romaji: ['itsuka'] },
      6: { hiragana: 'むいか', romaji: ['muika'] },
      7: { hiragana: 'なのか', romaji: ['nanoka'] },
      8: { hiragana: 'ようか', romaji: ['youka', 'yooka'] },
      9: { hiragana: 'ここのか', romaji: ['kokonoka'] },
      10: { hiragana: 'とおか', romaji: ['tooka', 'touka'] },
      11: { hiragana: 'じゅういちにち', romaji: ['juuichinichi', 'juichinichi'] },
      12: { hiragana: 'じゅうににち', romaji: ['juuninichi', 'juninichi'] },
      13: { hiragana: 'じゅうさんにち', romaji: ['juusannichi', 'jusannichi'] },
      14: { hiragana: 'じゅうよっか', romaji: ['juuyokka', 'juyokka'] },
      15: { hiragana: 'じゅうごにち', romaji: ['juugonichi', 'jugonichi'] },
      16: { hiragana: 'じゅうろくにち', romaji: ['juurokunichi', 'jurokunichi'] },
      17: { hiragana: 'じゅうしちにち', romaji: ['juushichinichi', 'jushichinichi', 'juunananichi'] },
      18: { hiragana: 'じゅうはちにち', romaji: ['juuhachinichi', 'juhachinichi'] },
      19: { hiragana: 'じゅうくにち', romaji: ['juukunichi', 'jukunichi'] },
      20: { hiragana: 'はつか', romaji: ['hatsuka'] },
      21: { hiragana: 'にじゅういちにち', romaji: ['nijuuichinichi', 'nijuichinichi'] },
      22: { hiragana: 'にじゅうににち', romaji: ['nijuuninichi', 'nijuninichi'] },
      23: { hiragana: 'にじゅうさんにち', romaji: ['nijuusannichi', 'nijusannichi'] },
      24: { hiragana: 'にじゅうよっか', romaji: ['nijuuyokka', 'nijuyokka'] },
      25: { hiragana: 'にじゅうごにち', romaji: ['nijuugonichi', 'nijugonichi'] },
      26: { hiragana: 'にじゅうろくにち', romaji: ['nijuurokunichi', 'nijurokunichi'] },
      27: { hiragana: 'にじゅうしちにち', romaji: ['nijuushichinichi', 'nijushichinichi', 'nijuunananichi'] },
      28: { hiragana: 'にじゅうはちにち', romaji: ['nijuuhachinichi', 'nijuhachinichi'] },
      29: { hiragana: 'にじゅうくにち', romaji: ['nijuukunichi', 'nijukunichi'] },
      30: { hiragana: 'さんじゅうにち', romaji: ['sanjuunichi', 'sanjunichi'] },
      31: { hiragana: 'さんじゅういちにち', romaji: ['sanjuuichinichi', 'sanjuichinichi'] }
  };
