const ADJECTIVES =[
    {word:'高い',kana:'たかい',meaning:'caro; alto',type:'i'},
    {word:'暑い',kana:'あつい',meaning:'quente (clima)',type:'i'},
    {word:'熱い',kana:'あつい',meaning:'quente (ao toque)',type:'i'},
    {word:'寒い',kana:'さむい',meaning:'frio (clima)',type:'i'},
    {word:'冷たい',kana:'つめたい',meaning:'frio (ao toque)',type:'i'},
    {word:'おいしい',kana:'おいしい',meaning:'delicioso',type:'i'},
    {word:'難しい',kana:'むずかしい',meaning:'difícil',type:'i'},
    {word:'忙しい',kana:'いそがしい',meaning:'ocupado; atarefado',type:'i'},
    {word:'新しい',kana:'あたらしい',meaning:'novo',type:'i'},
    {word:'古い',kana:'ふるい',meaning:'velho; antigo',type:'i'},
    {word:'大きい',kana:'おおきい',meaning:'grande',type:'i'},
    {word:'小さい',kana:'ちいさい',meaning:'pequeno',type:'i'},
    {word:'いい',kana:'いい',meaning:'bom',type:'i',exception:true},
    {word:'静か',kana:'しずか',meaning:'calmo; silencioso',type:'na'},
    {word:'暇',kana:'ひま',meaning:'livre; desocupado',type:'na'},
    {word:'きれい',kana:'きれい',meaning:'bonito; limpo',type:'na'},
    {word:'元気',kana:'げんき',meaning:'saudável; animado',type:'na'},
    {word:'便利',kana:'べんり',meaning:'conveniente; prático',type:'na'},
    {word:'有名',kana:'ゆうめい',meaning:'famoso',type:'na'},
    {word:'好き',kana:'すき',meaning:'de que gosta; favorito',type:'na'},
    {word:'嫌い',kana:'きらい',meaning:'de que não gosta',type:'na'},
    {word:'簡単',kana:'かんたん',meaning:'fácil; simples',type:'na'},
    {word:'危ない',kana:'あぶない',meaning:'perigoso',type:'i'},
    {word:'赤い',kana:'あかい',meaning:'vermelho; escarlate',type:'i'},
    {word:'明るい',kana:'あかるい',meaning:'claro; luminoso',type:'i'},
    {word:'甘い',kana:'あまい',meaning:'doce; indulgente; ingênuo',type:'i'},
    {word:'青い',kana:'あおい',meaning:'azul',type:'i'},
    {word:'暖かい',kana:'あたたかい',meaning:'morno; acolhedor',type:'i'},
    {word:'厚い',kana:'あつい',meaning:'espesso; grosso',type:'i'},
    {word:'近い',kana:'ちかい',meaning:'perto; próximo',type:'i'},
    {word:'大丈夫',kana:'だいじょうぶ',meaning:'bem; seguro; sem problemas',type:'na'},
    {word:'大好き',kana:'だいすき',meaning:'adorar; gostar muito',type:'na'},
    {word:'太い',kana:'ふとい',meaning:'grosso; robusto',type:'i'},
    {word:'速い',kana:'はやい',meaning:'rápido; veloz',type:'i'},
    {word:'早い',kana:'はやい',meaning:'cedo; rápido',type:'i'},
    {word:'下手',kana:'へた',meaning:'inábil; ruim em',type:'na'},
    {word:'低い',kana:'ひくい',meaning:'baixo',type:'i'},
    {word:'広い',kana:'ひろい',meaning:'amplo; espaçoso',type:'i'},
    {word:'本当',kana:'ほんとう',meaning:'verdadeiro; real',type:'na'},
    {word:'欲しい',kana:'ほしい',meaning:'querer; desejar',type:'i'},
    {word:'細い',kana:'ほそい',meaning:'fino; esbelto',type:'i'},
    {word:'色々',kana:'いろいろ',meaning:'variado; diverso',type:'na'},
    {word:'痛い',kana:'いたい',meaning:'dolorido; doloroso',type:'i'},
    {word:'嫌',kana:'いや',meaning:'desagradável; indesejado',type:'na'},
    {word:'丈夫',kana:'じょうぶ',meaning:'resistente; durável',type:'na'},
    {word:'上手',kana:'じょうず',meaning:'habilidoso; bom em',type:'na'},
    {word:'辛い',kana:'からい',meaning:'picante',type:'i'},
    {word:'軽い',kana:'かるい',meaning:'leve',type:'i'},
    {word:'可愛い',kana:'かわいい',meaning:'fofo; adorável',type:'i'},
    {word:'結構',kana:'けっこう',meaning:'ótimo; suficiente',type:'na'},
    {word:'黄色い',kana:'きいろい',meaning:'amarelo',type:'i'},
    {word:'綺麗',kana:'きれい',meaning:'bonito; limpo',type:'na'},
    {word:'汚い',kana:'きたない',meaning:'sujo',type:'i'},
    {word:'暗い',kana:'くらい',meaning:'escuro; sombrio',type:'i'},
    {word:'黒い',kana:'くろい',meaning:'preto',type:'i'},
    {word:'丸い',kana:'まるい',meaning:'redondo; circular',type:'i'},
    {word:'真っ直ぐ',kana:'まっすぐ',meaning:'reto; direto',type:'na'},
    {word:'不味い',kana:'まずい',meaning:'ruim (de sabor); desagradável',type:'i'},
    {word:'短い',kana:'みじかい',meaning:'curto',type:'i'},
    {word:'長い',kana:'ながい',meaning:'longo; comprido',type:'i'},
    {word:'賑やか',kana:'にぎやか',meaning:'movimentado; animado',type:'na'},
    {word:'温い',kana:'ぬるい',meaning:'morno',type:'i'},
    {word:'美味しい',kana:'おいしい',meaning:'delicioso; saboroso',type:'i'},
    {word:'重い',kana:'おもい',meaning:'pesado',type:'i'},
    {word:'面白い',kana:'おもしろい',meaning:'interessante; divertido',type:'i'},
    {word:'多い',kana:'おおい',meaning:'numeroso; frequente',type:'i'},
    {word:'遅い',kana:'おそい',meaning:'lento; atrasado; tarde',type:'i'},
    {word:'立派',kana:'りっぱ',meaning:'magnífico; admirável',type:'na'},
    {word:'狭い',kana:'せまい',meaning:'estreito; apertado',type:'i'},
    {word:'白い',kana:'しろい',meaning:'branco',type:'i'},
    {word:'少ない',kana:'すくない',meaning:'pouco; escasso',type:'i'},
    {word:'涼しい',kana:'すずしい',meaning:'fresco; agradável',type:'i'},
    {word:'大変',kana:'たいへん',meaning:'difícil; sério; muito',type:'na'},
    {word:'大切',kana:'たいせつ',meaning:'importante; precioso',type:'na'},
    {word:'沢山',kana:'たくさん',meaning:'muito; em grande quantidade',type:'na'},
    {word:'楽しい',kana:'たのしい',meaning:'divertido; agradável',type:'i'},
    {word:'遠い',kana:'とおい',meaning:'distante; longe',type:'i'},
    {word:'詰まらない',kana:'つまらない',meaning:'entediante; sem graça',type:'i'},
    {word:'強い',kana:'つよい',meaning:'forte; poderoso',type:'i'},
    {word:'煩い',kana:'うるさい',meaning:'barulhento; irritante',type:'i'},
    {word:'薄い',kana:'うすい',meaning:'fino; fraco; aguado',type:'i'},
    {word:'若い',kana:'わかい',meaning:'jovem',type:'i'},
    {word:'悪い',kana:'わるい',meaning:'ruim; mau',type:'i'},
    {word:'易しい',kana:'やさしい',meaning:'fácil; simples',type:'i'},
    {word:'安い',kana:'やすい',meaning:'barato',type:'i'},
    {word:'良い',kana:'よい',meaning:'bom',type:'i',exception:true},
    {word:'弱い',kana:'よわい',meaning:'fraco',type:'i'}
  ];
