const VERBS =[
    {v:'浴びる',ruby:'<ruby>浴<rt>あ</rt></ruby>びる',kana:'あびる',te:'あびて',kanji:'浴びて',g:'ichidan',rule:'grupo 2: る → て', translation: 'tomar banho'},
    {v:'上げる',ruby:'<ruby>上<rt>あ</rt></ruby>げる',kana:'あげる',te:'あげて',kanji:'上げて',g:'ichidan',rule:'grupo 2: る → て', translation: 'levantar; elevar; dar'},
    {v:'開ける',ruby:'<ruby>開<rt>あ</rt></ruby>ける',kana:'あける',te:'あけて',kanji:'開けて',g:'ichidan',rule:'grupo 2: る → て', translation: 'abrir (uma porta, etc.); desembrulhar (pacote); destrancar'},
    {v:'開く',ruby:'<ruby>開<rt>あ</rt></ruby>く',kana:'あく',te:'あいて',kanji:'開いて',g:'godan',rule:'く → いて', translation: 'abrir (portas, negócios, etc.)'},
    {v:'洗う',ruby:'<ruby>洗<rt>あら</rt></ruby>う',kana:'あらう',te:'あらって',kanji:'洗って',g:'godan',rule:'う → って', translation: 'lavar'},
    {v:'ある',kana:'ある',te:'あって',kanji:'あって',g:'godan',rule:'る (grupo 1) → って', translation: 'haver; ter'},
    {v:'歩く',ruby:'<ruby>歩<rt>ある</rt></ruby>く',kana:'あるく',te:'あるいて',kanji:'歩いて',g:'godan',rule:'く → いて', translation: 'andar'},
    {v:'遊ぶ',ruby:'<ruby>遊<rt>あそ</rt></ruby>ぶ',kana:'あそぶ',te:'あそんで',kanji:'遊んで',g:'godan',rule:'ぶ → んで', translation: 'brincar; divertir-se'},
    {v:'会う',ruby:'<ruby>会<rt>あ</rt></ruby>う',kana:'あう',te:'あって',kanji:'会って',g:'godan',rule:'う → って', translation: 'encontrar; ver'},
    {v:'勉強する',ruby:'<ruby>勉強<rt>べんきょう</rt></ruby>する',kana:'べんきょうする',te:'べんきょうして',kanji:'勉強して',g:'irregular',rule:'する → して', translation: 'estudar'},
    {v:'違う',ruby:'<ruby>違<rt>ちが</rt></ruby>う',kana:'ちがう',te:'ちがって',kanji:'違って',g:'godan',rule:'う → って', translation: 'diferir'},
    {v:'出す',ruby:'<ruby>出<rt>だ</rt></ruby>す',kana:'だす',te:'だして',kanji:'出して',g:'godan',rule:'す → して', translation: 'tirar; retirar; colocar para fora; revelar'},
    {v:'出かける',ruby:'<ruby>出<rt>で</rt></ruby>かける',kana:'でかける',te:'でかけて',kanji:'出かけて',g:'ichidan',rule:'grupo 2: る → て', translation: 'sair; partir'},
    {v:'電話する',ruby:'<ruby>電話<rt>でんわ</rt></ruby>する',kana:'でんわする',te:'でんわして',kanji:'電話して',g:'irregular',rule:'する → して', translation: 'telefonar; ligar'},
    {v:'出る',ruby:'<ruby>出<rt>で</rt></ruby>る',kana:'でる',te:'でて',kanji:'出て',g:'ichidan',rule:'grupo 2: る → て', translation: 'sair; aparecer'},
    {v:'吹く',ruby:'<ruby>吹<rt>ふ</rt></ruby>く',kana:'ふく',te:'ふいて',kanji:'吹いて',g:'godan',rule:'く → いて', translation: 'soprar (vento)'},
    {v:'降る',ruby:'<ruby>降<rt>ふ</rt></ruby>る',kana:'ふる',te:'ふって',kanji:'降って',g:'godan',rule:'る (grupo 1) → って', translation: 'cair (chuva, neve)'},
    {v:'入る',ruby:'<ruby>入<rt>はい</rt></ruby>る',kana:'はいる',te:'はいって',kanji:'入って',g:'godan',rule:'る (grupo 1) → って', translation: 'entrar'},
    {v:'始まる',ruby:'<ruby>始<rt>はじ</rt></ruby>まる',kana:'はじまる',te:'はじまって',kanji:'始まって',g:'godan',rule:'る (grupo 1) → って', translation: 'começar'},
    {v:'履く',ruby:'<ruby>履<rt>は</rt></ruby>く',kana:'はく',te:'はいて',kanji:'履いて',g:'godan',rule:'く → いて', translation: 'vestir (calças, sapatos)'},
    {v:'話す',ruby:'<ruby>話<rt>はな</rt></ruby>す',kana:'はなす',te:'はなして',kanji:'話して',g:'godan',rule:'す → して', translation: 'falar; conversar'},
    {v:'晴れる',ruby:'<ruby>晴<rt>は</rt></ruby>れる',kana:'はれる',te:'はれて',kanji:'晴れて',g:'ichidan',rule:'grupo 2: る → て', translation: 'ficar ensolarado'},
    {v:'貼る',ruby:'<ruby>貼<rt>は</rt></ruby>る',kana:'はる',te:'はって',kanji:'貼って',g:'godan',rule:'る (grupo 1) → って', translation: 'colar; pregar'},
    {v:'走る',ruby:'<ruby>走<rt>はし</rt></ruby>る',kana:'はしる',te:'はしって',kanji:'走って',g:'godan',rule:'る (grupo 1) → って', translation: 'correr'},
    {v:'働く',ruby:'<ruby>働<rt>はたら</rt></ruby>く',kana:'はたらく',te:'はたらいて',kanji:'働いて',g:'godan',rule:'く → いて', translation: 'trabalhar'},
    {v:'引く',ruby:'<ruby>引<rt>ひ</rt></ruby>く',kana:'ひく',te:'ひいて',kanji:'引いて',g:'godan',rule:'く → いて', translation: 'puxar'},
    {v:'弾く',ruby:'<ruby>弾<rt>ひ</rt></ruby>く',kana:'ひく',te:'ひいて',kanji:'弾いて',g:'godan',rule:'く → いて', translation: 'tocar (instrumento)'},
    {v:'行く',ruby:'<ruby>行<rt>い</rt></ruby>く',kana:'いく',te:'いって',kanji:'行って',g:'irregular',rule:'exceção: 行く → 行って', translation: 'ir; mover-se'},
    {v:'入れる',ruby:'<ruby>入<rt>い</rt></ruby>れる',kana:'いれる',te:'いれて',kanji:'入れて',g:'ichidan',rule:'grupo 2: る → て', translation: 'colocar; inserir; instalar'},
    {v:'要る',ruby:'<ruby>要<rt>い</rt></ruby>る',kana:'いる',te:'いって',kanji:'要って',g:'godan',rule:'る (grupo 1) → って', translation: 'ser necessário'},
    {v:'居る',ruby:'<ruby>居<rt>い</rt></ruby>る',kana:'いる',te:'いて',kanji:'居て',g:'ichidan',rule:'grupo 2: る → て', translation: 'estar; ter'},
    {v:'言う',ruby:'<ruby>言<rt>い</rt></ruby>う',kana:'いう',te:'いって',kanji:'言って',g:'godan',rule:'う → って', translation: 'dizer; chamar'},
    {v:'授業する',ruby:'<ruby>授業<rt>じゅぎょう</rt></ruby>する',kana:'じゅぎょうする',te:'じゅぎょうして',kanji:'授業して',g:'irregular',rule:'する → して', translation: 'dar aula; ter aula'},
    {v:'帰る',ruby:'<ruby>帰<rt>かえ</rt></ruby>る',kana:'かえる',te:'かえって',kanji:'帰って',g:'godan',rule:'る (grupo 1) → って', translation: 'voltar para casa'},
    {v:'返す',ruby:'<ruby>返<rt>かえ</rt></ruby>す',kana:'かえす',te:'かえして',kanji:'返して',g:'godan',rule:'す → して', translation: 'devolver algo'},
    {v:'掛かる',ruby:'<ruby>掛<rt>か</rt></ruby>かる',kana:'かかる',te:'かかって',kanji:'掛かって',g:'godan',rule:'る (grupo 1) → って', translation: 'levar (tempo ou dinheiro)'},
    {v:'掛ける',ruby:'<ruby>掛<rt>か</rt></ruby>ける',kana:'かける',te:'かけて',kanji:'掛けて',g:'ichidan',rule:'grupo 2: る → て', translation: 'pendurar; fazer (uma ligação)'},
    {v:'書く',ruby:'<ruby>書<rt>か</rt></ruby>く',kana:'かく',te:'かいて',kanji:'書いて',g:'godan',rule:'く → いて', translation: 'escrever; compor; desenhar'},
    {v:'借りる',ruby:'<ruby>借<rt>か</rt></ruby>りる',kana:'かりる',te:'かりて',kanji:'借りて',g:'ichidan',rule:'grupo 2: る → て', translation: 'emprestar'},
    {v:'貸す',ruby:'<ruby>貸<rt>か</rt></ruby>す',kana:'かす',te:'かして',kanji:'貸して',g:'godan',rule:'す → して', translation: 'emprestar; conceder'},
    {v:'買う',ruby:'<ruby>買<rt>か</rt></ruby>う',kana:'かう',te:'かって',kanji:'買って',g:'godan',rule:'う → って', translation: 'comprar'},
    {v:'結婚する',ruby:'<ruby>結婚<rt>けっこん</rt></ruby>する',kana:'けっこんする',te:'けっこんして',kanji:'結婚して',g:'irregular',rule:'する → して', translation: 'casar'},
    {v:'消す',ruby:'<ruby>消<rt>け</rt></ruby>す',kana:'けす',te:'けして',kanji:'消して',g:'godan',rule:'す → して', translation: 'apagar; desligar (energia)'},
    {v:'消える',ruby:'<ruby>消<rt>き</rt></ruby>える',kana:'きえる',te:'きえて',kanji:'消えて',g:'ichidan',rule:'grupo 2: る → て', translation: 'desaparecer'},
    {v:'聞く',ruby:'<ruby>聞<rt>き</rt></ruby>く',kana:'きく',te:'きいて',kanji:'聞いて',g:'godan',rule:'く → いて', translation: 'ouvir; escutar; perguntar; aprender'},
    {v:'切る',ruby:'<ruby>切<rt>き</rt></ruby>る',kana:'きる',te:'きって',kanji:'切って',g:'godan',rule:'る (grupo 1) → って', translation: 'cortar'},
    {v:'着る',ruby:'<ruby>着<rt>き</rt></ruby>る',kana:'きる',te:'きて',kanji:'着て',g:'ichidan',rule:'grupo 2: る → て', translation: 'vestir (roupas)'},
    {v:'困る',ruby:'<ruby>困<rt>こま</rt></ruby>る',kana:'こまる',te:'こまって',kanji:'困って',g:'godan',rule:'る (grupo 1) → って', translation: 'estar com problemas'},
    {v:'コピーする',kana:'こぴーする',te:'こぴーして',kanji:'コピーして',g:'irregular',rule:'する → して', translation: 'copiar; fotocopiar'},
    {v:'答える',ruby:'<ruby>答<rt>こた</rt></ruby>える',kana:'こたえる',te:'こたえて',kanji:'答えて',g:'ichidan',rule:'grupo 2: る → て', translation: 'responder'},
    {v:'曇る',ruby:'<ruby>曇<rt>くも</rt></ruby>る',kana:'くもる',te:'くもって',kanji:'曇って',g:'godan',rule:'る (grupo 1) → って', translation: 'ficar nublado; ficar embaçado'},
    {v:'来る',ruby:'<ruby>来<rt>く</rt></ruby>る',kana:'くる',te:'きて',kanji:'来て',g:'irregular',rule:'来る（くる）→ 来て（きて）', translation: 'vir'},
    {v:'曲がる',ruby:'<ruby>曲<rt>ま</rt></ruby>がる',kana:'まがる',te:'まがって',kanji:'曲がって',g:'godan',rule:'る (grupo 1) → って', translation: 'virar; dobrar'},
    {v:'待つ',ruby:'<ruby>待<rt>ま</rt></ruby>つ',kana:'まつ',te:'まって',kanji:'待って',g:'godan',rule:'つ → って', translation: 'esperar'},
    {v:'磨く',ruby:'<ruby>磨<rt>みが</rt></ruby>く',kana:'みがく',te:'みがいて',kanji:'磨いて',g:'godan',rule:'く → いて', translation: 'polir; lustrar; escovar (dentes)'},
    {v:'見る',ruby:'<ruby>見<rt>み</rt></ruby>る',kana:'みる',te:'みて',kanji:'見て',g:'ichidan',rule:'grupo 2: る → て', translation: 'ver; olhar; assistir; observar'},
    {v:'見せる',ruby:'<ruby>見<rt>み</rt></ruby>せる',kana:'みせる',te:'みせて',kanji:'見せて',g:'ichidan',rule:'grupo 2: る → て', translation: 'mostrar; exibir'},
    {v:'持つ',ruby:'<ruby>持<rt>も</rt></ruby>つ',kana:'もつ',te:'もって',kanji:'持って',g:'godan',rule:'つ → って', translation: 'segurar; ter'},
    {v:'鳴く',ruby:'<ruby>鳴<rt>な</rt></ruby>く',kana:'なく',te:'ないて',kanji:'鳴いて',g:'godan',rule:'く → いて', translation: 'fazer barulho de animal; piar'},
    {v:'無くす',ruby:'<ruby>無<rt>な</rt></ruby>くす',kana:'なくす',te:'なくして',kanji:'無くして',g:'godan',rule:'す → して', translation: 'perder (algo)'},
    {v:'並べる',ruby:'<ruby>並<rt>なら</rt></ruby>べる',kana:'ならべる',te:'ならべて',kanji:'並べて',g:'ichidan',rule:'grupo 2: る → て', translation: 'alinhar; organizar'},
    {v:'並ぶ',ruby:'<ruby>並<rt>なら</rt></ruby>ぶ',kana:'ならぶ',te:'ならんで',kanji:'並んで',g:'godan',rule:'ぶ → んで', translation: 'alinhar-se; ficar em fila'},
    {v:'習う',ruby:'<ruby>習<rt>なら</rt></ruby>う',kana:'ならう',te:'ならって',kanji:'習って',g:'godan',rule:'う → って', translation: 'aprender (com um professor)'},
    {v:'寝る',ruby:'<ruby>寝<rt>ね</rt></ruby>る',kana:'ねる',te:'ねて',kanji:'寝て',g:'ichidan',rule:'grupo 2: る → て', translation: 'dormir; ir para a cama; deitar-se'},
    {v:'登る',ruby:'<ruby>登<rt>のぼ</rt></ruby>る',kana:'のぼる',te:'のぼって',kanji:'登って',g:'godan',rule:'る (grupo 1) → って', translation: 'subir; escalar'},
    {v:'飲む',ruby:'<ruby>飲<rt>の</rt></ruby>む',kana:'のむ',te:'のんで',kanji:'飲んで',g:'godan',rule:'む → んで', translation: 'beber'},
    {v:'乗る',ruby:'<ruby>乗<rt>の</rt></ruby>る',kana:'のる',te:'のって',kanji:'乗って',g:'godan',rule:'る (grupo 1) → って', translation: 'embarcar (em trem, avião, ônibus, navio, etc.)'},
    {v:'脱ぐ',ruby:'<ruby>脱<rt>ぬ</rt></ruby>ぐ',kana:'ぬぐ',te:'ぬいで',kanji:'脱いで',g:'godan',rule:'ぐ → いで', translation: 'tirar (roupas)'},
    {v:'覚える',ruby:'<ruby>覚<rt>おぼ</rt></ruby>える',kana:'おぼえる',te:'おぼえて',kanji:'覚えて',g:'ichidan',rule:'grupo 2: る → て', translation: 'lembrar; memorizar'},
    {v:'起きる',ruby:'<ruby>起<rt>お</rt></ruby>きる',kana:'おきる',te:'おきて',kanji:'起きて',g:'ichidan',rule:'grupo 2: る → て', translation: 'levantar; acordar'},
    {v:'置く',ruby:'<ruby>置<rt>お</rt></ruby>く',kana:'おく',te:'おいて',kanji:'置いて',g:'godan',rule:'く → いて', translation: 'colocar; pôr'},
    {v:'降りる',ruby:'<ruby>降<rt>お</rt></ruby>りる',kana:'おりる',te:'おりて',kanji:'降りて',g:'ichidan',rule:'grupo 2: る → て', translation: 'descer'},
    {v:'教える',ruby:'<ruby>教<rt>おし</rt></ruby>える',kana:'おしえる',te:'おしえて',kanji:'教えて',g:'ichidan',rule:'grupo 2: る → て', translation: 'ensinar'},
    {v:'押す',ruby:'<ruby>押<rt>お</rt></ruby>す',kana:'おす',te:'おして',kanji:'押して',g:'godan',rule:'す → して', translation: 'empurrar; pressionar'},
    {v:'終わる',ruby:'<ruby>終<rt>お</rt></ruby>わる',kana:'おわる',te:'おわって',kanji:'終わって',g:'godan',rule:'る (grupo 1) → って', translation: 'terminar; acabar'},
    {v:'泳ぐ',ruby:'<ruby>泳<rt>およ</rt></ruby>ぐ',kana:'およぐ',te:'およいで',kanji:'泳いで',g:'godan',rule:'ぐ → いで', translation: 'nadar'},
    {v:'練習する',ruby:'<ruby>練習<rt>れんしゅう</rt></ruby>する',kana:'れんしゅうする',te:'れんしゅうして',kanji:'練習して',g:'irregular',rule:'する → して', translation: 'praticar'},
    {v:'旅行する',ruby:'<ruby>旅行<rt>りょこう</rt></ruby>する',kana:'りょこうする',te:'りょこうして',kanji:'旅行して',g:'irregular',rule:'する → して', translation: 'viajar; fazer uma viagem'},
    {v:'料理する',ruby:'<ruby>料理<rt>りょうり</rt></ruby>する',kana:'りょうりする',te:'りょうりして',kanji:'料理して',g:'irregular',rule:'する → して', translation: 'cozinhar'},
    {v:'咲く',ruby:'<ruby>咲<rt>さ</rt></ruby>く',kana:'さく',te:'さいて',kanji:'咲いて',g:'godan',rule:'く → いて', translation: 'florescer'},
    {v:'散歩する',ruby:'<ruby>散歩<rt>さんぽ</rt></ruby>する',kana:'さんぽする',te:'さんぽして',kanji:'散歩して',g:'irregular',rule:'する → して', translation: 'caminhar; passear'},
    {v:'差す',ruby:'<ruby>差<rt>さ</rt></ruby>す',kana:'さす',te:'さして',kanji:'差して',g:'godan',rule:'す → して', translation: 'estender as mãos; levantar um guarda-chuva'},
    {v:'洗濯する',ruby:'<ruby>洗濯<rt>せんたく</rt></ruby>する',kana:'せんたくする',te:'せんたくして',kanji:'洗濯して',g:'irregular',rule:'する → して', translation: 'lavar roupa; fazer a lavanderia'},
    {v:'仕事する',ruby:'<ruby>仕事<rt>しごと</rt></ruby>する',kana:'しごとする',te:'しごとして',kanji:'仕事して',g:'irregular',rule:'する → して', translation: 'trabalhar; fazer um trabalho'},
    {v:'閉まる',ruby:'<ruby>閉<rt>し</rt></ruby>まる',kana:'しまる',te:'しまって',kanji:'閉まって',g:'godan',rule:'る (grupo 1) → って', translation: 'fechar-se; estar fechado'},
    {v:'閉める',ruby:'<ruby>閉<rt>し</rt></ruby>める',kana:'しめる',te:'しめて',kanji:'閉めて',g:'ichidan',rule:'grupo 2: る → て', translation: 'fechar; trancar'},
    {v:'締める',ruby:'<ruby>締<rt>し</rt></ruby>める',kana:'しめる',te:'しめて',kanji:'締めて',g:'ichidan',rule:'grupo 2: る → て', translation: 'amarrar; apertar'},
    {v:'死ぬ',ruby:'<ruby>死<rt>し</rt></ruby>ぬ',kana:'しぬ',te:'しんで',kanji:'死んで',g:'godan',rule:'ぬ → んで', translation: 'morrer'},
    {v:'知る',ruby:'<ruby>知<rt>し</rt></ruby>る',kana:'しる',te:'しって',kanji:'知って',g:'godan',rule:'る (grupo 1) → って', translation: 'saber; conhecer'},
    {v:'質問する',ruby:'<ruby>質問<rt>しつもん</rt></ruby>する',kana:'しつもんする',te:'しつもんして',kanji:'質問して',g:'irregular',rule:'する → して', translation: 'perguntar; fazer uma pergunta'},
    {v:'掃除する',ruby:'<ruby>掃除<rt>そうじ</rt></ruby>する',kana:'そうじする',te:'そうじして',kanji:'掃除して',g:'irregular',rule:'する → して', translation: 'limpar; varrer'},
    {v:'住む',ruby:'<ruby>住<rt>す</rt></ruby>む',kana:'すむ',te:'すんで',kanji:'住んで',g:'godan',rule:'む → んで', translation: 'morar; residir'},
    {v:'吸う',ruby:'<ruby>吸<rt>す</rt></ruby>う',kana:'すう',te:'すって',kanji:'吸って',g:'godan',rule:'う → って', translation: 'fumar; sugar'},
    {v:'座る',ruby:'<ruby>座<rt>すわ</rt></ruby>る',kana:'すわる',te:'すわって',kanji:'座って',g:'godan',rule:'る (grupo 1) → って', translation: 'sentar'},
    {v:'食べる',ruby:'<ruby>食<rt>た</rt></ruby>べる',kana:'たべる',te:'たべて',kanji:'食べて',g:'ichidan',rule:'grupo 2: る → て', translation: 'comer'},
    {v:'頼む',ruby:'<ruby>頼<rt>たの</rt></ruby>む',kana:'たのむ',te:'たのんで',kanji:'頼んで',g:'godan',rule:'む → んで', translation: 'pedir'},
    {v:'立つ',ruby:'<ruby>立<rt>た</rt></ruby>つ',kana:'たつ',te:'たって',kanji:'立って',g:'godan',rule:'つ → って', translation: 'ficar em pé; levantar'},
    {v:'テストする',kana:'てすとする',te:'てすとして',kanji:'テストして',g:'irregular',rule:'する → して', translation: 'fazer um teste; testar'},
    {v:'飛ぶ',ruby:'<ruby>飛<rt>と</rt></ruby>ぶ',kana:'とぶ',te:'とんで',kanji:'飛んで',g:'godan',rule:'ぶ → んで', translation: 'voar; pular'},
    {v:'止まる',ruby:'<ruby>止<rt>と</rt></ruby>まる',kana:'とまる',te:'とまって',kanji:'止まって',g:'godan',rule:'る (grupo 1) → って', translation: 'parar; deter-se'}
];
